[MAIN]
starting-window-size	= (1000,1000)
scroll-modifier			= 50

[COLOR]
button-color		= (40, 23, 57)
accent-color		= (40, 23, 57)
background-color    = (10, 10, 15)
font-color			= (79, 117, 189)

[FONT]
font				= 'defaultFont.ttf' # set this to 'system-font' if you want to use your systems font
font-size			= 14
